name: AngelSkyCoalitions
version: '${project.version}'
main: fr.angelsky.angelskycoalitions.AngelSkyCoalitions
api-version: 1.20
dependencies:
  - AngelskyApi
authors: [Ariouz]
commands:
  setplayercoalition:
    description: Définir la coalition d'un joueur
  coalitions:
    description: Commande coalitions
    aliases:
      - coalition
      - coa
